name: Code Format CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install black and isort
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Run black
        run: black .

      - name: Run isort 
        run: isort .
      - name: Commit and push formatted code
        run: |
          git config --global user.email "ci-bot@example.com"
          git config --global user.name "CI Bot"
          git add .
          git commit -m "Auto-format code"
          git push origin ${{ github.ref }}
        continue-on-error: true  # Si no hay cambios, evitar error